// screens/chat/chat_screen.dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:innercircle/blocs/chat/chat_bloc.dart';
import 'package:innercircle/blocs/chat/chat_event.dart' as chat_event;
import 'package:innercircle/blocs/chat/chat_state.dart';
import 'package:innercircle/core/theme/app_colors.dart';
import 'package:innercircle/core/theme/app_dimensions.dart';
import 'package:innercircle/core/theme/app_text_styles.dart';
import 'package:innercircle/data/models/app_user.dart';
import 'package:innercircle/data/models/event.dart';
import 'package:innercircle/data/models/message.dart';
import 'package:intl/intl.dart';

class ChatScreen extends StatefulWidget {
  final Event event;
  final AppUser currentUser;

  const ChatScreen({Key? key, required this.event, required this.currentUser})
    : super(key: key);

  @override
  State<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    context.read<ChatBloc>().add(chat_event.ChatLoadRequested(widget.event.id));
  }

  void _sendMessage() {
    final text = _messageController.text.trim();
    if (text.isEmpty) return;

    final message = ChatMessage(
      id: '', // Will be generated by Firestore
      text: text,
      senderId: widget.currentUser.uid,
      senderName: widget.currentUser.name,
      senderPhotoUrl: widget.currentUser.photoUrl,
      timestamp: DateTime.now(),
    );

    context.read<ChatBloc>().add(
      chat_event.ChatMessageSent(widget.event.id, message),
    );

    _messageController.clear();

    // Scroll to bottom after sending
    Future.delayed(const Duration(milliseconds: 100), () {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          0,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              widget.event.title,
              style: AppTextStyles.bodyMedium.copyWith(fontSize: 16),
            ),
            Text(
              '${widget.event.joinedUsers.length} participants',
              style: AppTextStyles.caption.copyWith(fontSize: 11),
            ),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.info_outline),
            onPressed: () {
              // Navigate back to event details
              Navigator.pop(context);
            },
          ),
        ],
      ),
      body: Column(
        children: [
          // Messages List
          Expanded(
            child: BlocBuilder<ChatBloc, ChatState>(
              builder: (context, state) {
                if (state is ChatLoading) {
                  return const Center(child: CircularProgressIndicator());
                }

                if (state is ChatError) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.error_outline,
                          size: 64,
                          color: AppColors.error,
                        ),
                        SizedBox(height: AppDimensions.spacingM),
                        Text(
                          'Error loading chat',
                          style: AppTextStyles.subheading,
                        ),
                        SizedBox(height: AppDimensions.spacingS),
                        Text(state.message, style: AppTextStyles.body),
                      ],
                    ),
                  );
                }

                if (state is ChatLoaded) {
                  final messages = state.messages;

                  if (messages.isEmpty) {
                    return Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(
                            Icons.chat_bubble_outline,
                            size: 64,
                            color: AppColors.textSecondary,
                          ),
                          SizedBox(height: AppDimensions.spacingM),
                          Text(
                            'No messages yet',
                            style: AppTextStyles.subheading,
                          ),
                          SizedBox(height: AppDimensions.spacingS),
                          Text(
                            'Be the first to say hi!',
                            style: AppTextStyles.body,
                          ),
                        ],
                      ),
                    );
                  }

                  return ListView.builder(
                    controller: _scrollController,
                    reverse: true,
                    padding: EdgeInsets.all(AppDimensions.spacingM),
                    itemCount: messages.length,
                    itemBuilder: (context, index) {
                      final message = messages[index];
                      final isMe = message.senderId == widget.currentUser.uid;

                      // Show date separator
                      bool showDateSeparator = false;
                      if (index == messages.length - 1) {
                        showDateSeparator = true;
                      } else {
                        final nextMessage = messages[index + 1];
                        if (!_isSameDay(
                          message.timestamp,
                          nextMessage.timestamp,
                        )) {
                          showDateSeparator = true;
                        }
                      }

                      return Column(
                        children: [
                          if (showDateSeparator)
                            _buildDateSeparator(message.timestamp),
                          _buildMessageBubble(message, isMe),
                        ],
                      );
                    },
                  );
                }

                return const SizedBox.shrink();
              },
            ),
          ),

          // Input Field
          _buildInputField(),
        ],
      ),
    );
  }

  Widget _buildDateSeparator(DateTime date) {
    String dateText;
    final now = DateTime.now();

    if (_isSameDay(date, now)) {
      dateText = 'Today';
    } else if (_isSameDay(date, now.subtract(const Duration(days: 1)))) {
      dateText = 'Yesterday';
    } else {
      dateText = DateFormat('MMM dd, yyyy').format(date);
    }

    return Padding(
      padding: EdgeInsets.symmetric(vertical: AppDimensions.spacingM),
      child: Container(
        padding: EdgeInsets.symmetric(
          horizontal: AppDimensions.spacingM,
          vertical: AppDimensions.spacingS,
        ),
        decoration: BoxDecoration(
          color: AppColors.grey200,
          borderRadius: BorderRadius.circular(AppDimensions.radiusCircular),
        ),
        child: Text(
          dateText,
          style: AppTextStyles.caption.copyWith(fontWeight: FontWeight.w600),
        ),
      ),
    );
  }

  Widget _buildMessageBubble(ChatMessage message, bool isMe) {
    return Padding(
      padding: EdgeInsets.only(bottom: AppDimensions.spacingS),
      child: Row(
        mainAxisAlignment:
            isMe ? MainAxisAlignment.end : MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          if (!isMe) ...[
            CircleAvatar(
              radius: 16,
              backgroundColor: AppColors.primary,
              backgroundImage:
                  message.senderPhotoUrl != null
                      ? NetworkImage(message.senderPhotoUrl!)
                      : null,
              child:
                  message.senderPhotoUrl == null
                      ? Text(
                        message.senderName[0].toUpperCase(),
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                        ),
                      )
                      : null,
            ),
            SizedBox(width: AppDimensions.spacingS),
          ],
          Flexible(
            child: Column(
              crossAxisAlignment:
                  isMe ? CrossAxisAlignment.end : CrossAxisAlignment.start,
              children: [
                if (!isMe)
                  Padding(
                    padding: EdgeInsets.only(
                      left: AppDimensions.spacingS,
                      bottom: AppDimensions.spacingXS,
                    ),
                    child: Text(
                      message.senderName,
                      style: AppTextStyles.caption.copyWith(
                        fontWeight: FontWeight.w600,
                        color: AppColors.primary,
                      ),
                    ),
                  ),
                Container(
                  padding: EdgeInsets.symmetric(
                    horizontal: AppDimensions.spacingM,
                    vertical: AppDimensions.spacingS,
                  ),
                  decoration: BoxDecoration(
                    color: isMe ? AppColors.primary : AppColors.grey100,
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(AppDimensions.radiusM),
                      topRight: Radius.circular(AppDimensions.radiusM),
                      bottomLeft: Radius.circular(
                        isMe ? AppDimensions.radiusM : AppDimensions.radiusS,
                      ),
                      bottomRight: Radius.circular(
                        isMe ? AppDimensions.radiusS : AppDimensions.radiusM,
                      ),
                    ),
                  ),
                  child: Text(
                    message.text,
                    style: AppTextStyles.body.copyWith(
                      color: isMe ? Colors.white : AppColors.textPrimary,
                    ),
                  ),
                ),
                SizedBox(height: AppDimensions.spacingXS),
                Padding(
                  padding: EdgeInsets.symmetric(
                    horizontal: AppDimensions.spacingS,
                  ),
                  child: Text(
                    DateFormat('h:mm a').format(message.timestamp),
                    style: AppTextStyles.caption.copyWith(fontSize: 10),
                  ),
                ),
              ],
            ),
          ),
          if (isMe) SizedBox(width: AppDimensions.spacingS),
        ],
      ),
    );
  }

  Widget _buildInputField() {
    return Container(
      padding: EdgeInsets.all(AppDimensions.spacingM),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SafeArea(
        child: Row(
          children: [
            Expanded(
              child: TextField(
                controller: _messageController,
                decoration: InputDecoration(
                  hintText: 'Type a message...',
                  hintStyle: AppTextStyles.body.copyWith(
                    color: AppColors.textSecondary,
                  ),
                  filled: true,
                  fillColor: AppColors.grey100,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(
                      AppDimensions.radiusCircular,
                    ),
                    borderSide: BorderSide.none,
                  ),
                  contentPadding: EdgeInsets.symmetric(
                    horizontal: AppDimensions.spacingM,
                    vertical: AppDimensions.spacingS,
                  ),
                ),
                maxLines: null,
                textCapitalization: TextCapitalization.sentences,
              ),
            ),
            SizedBox(width: AppDimensions.spacingS),
            Container(
              decoration: BoxDecoration(
                color: AppColors.primary,
                shape: BoxShape.circle,
              ),
              child: IconButton(
                icon: const Icon(Icons.send, color: Colors.white),
                onPressed: _sendMessage,
              ),
            ),
          ],
        ),
      ),
    );
  }

  bool _isSameDay(DateTime date1, DateTime date2) {
    return date1.year == date2.year &&
        date1.month == date2.month &&
        date1.day == date2.day;
  }

  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }
}
